* Inlists for Papers using MESA
This repository contains the inlists, models, and other information
from my papers using MESA.  There is one folder per paper, named by
the ADS bibcode of the paper.
** 2015ApJS..220...15P
[[http://adsabs.harvard.edu/abs/2015ApJS..220...15P][Paxton et al. (2015)]]

Modules for Experiments in Stellar Astrophysics (MESA): Binaries, Pulsations, and Explosions

Materials have been updated to reflect the [[http://adsabs.harvard.edu/abs/2016ApJS..223...18P][published erratum]].
** 2015MNRAS.453.1910S
[[http://adsabs.harvard.edu/abs/2015MNRAS.453.1910S][Schwab et al. (2015)]]

Thermal Runaway During the Evolution of ONeMg Cores towards Accretion-Induced Collapse

Materials have been updated to reflect the [[http://adsabs.harvard.edu/abs/2016MNRAS.458.3613S][published erratum]].
** 2016MNRAS.463.3461S
[[http://adsabs.harvard.edu/abs/2016MNRAS.463.3461S][Schwab et al. (2016)]]

The Evolution and Fate of Super-Chandrasekhar Mass White Dwarf Merger Remnants
** 2016ApJ...832...71L
[[http://adsabs.harvard.edu/abs/2016ApJ...832...71L][Lecoanet et al. (2016)]]

Turbulent Chemical Diffusion in Convectively Bounded Carbon Flames
** 2017MNRAS.472.3390S
[[http://adsabs.harvard.edu/abs/2017MNRAS.472.3390S][Schwab et al. (2017)]]

The Importance of Urca-process Cooling in Accreting ONe White Dwarfs
** 2017ApJ...851..105S
[[http://adsabs.harvard.edu/abs/2017ApJ...851..105S][Schwab et al. (2017)]]

Exploring the Carbon Simmering Phase: Reaction Rates, Mixing, and the Convective Urca Process
** 2018MNRAS.476.5303S
[[http://adsabs.harvard.edu/abs/2018MNRAS.476.5303S][Schwab (2018)]]

Hot subdwarfs formed from the merger of two He white dwarfs
** 2019ApJ...872..131S
[[http://adsabs.harvard.edu/abs/2019ApJ...872..131S][Schwab and Rocha (2019)]]

Residual Carbon in Oxygen–Neon White Dwarfs and Its Implications for Accretion-induced Collapse
** 2019arXiv190902569S
[[https://ui.adsabs.harvard.edu/abs/2019arXiv190902569S/abstract][Schwab (2019)]]

Evolutionary models for R Coronae Borealis stars
