* mesa-RCrB
The inlists included here were run with MESA r11701.

The following scripts generate the inlists and run the models from the
paper.  The ruby scripts make use of Bill Wolf's [[https://github.com/wmwolf/MesaScript][MesaScript]].

** He star models 
The ruby scripts =compositions.rb=, =masses.rb=, and =metallicity.rb=
auto-generate inlists.  (Some other inlists were generated manually.)
These files are in =inlists/=.  Then the script =batch.sh= handles
running these collections of inlists through =masses.batch=,
=metallicity.batch=, =weiss.batch=, =bc.batch=, =A00.batch=.

** Merger models
The ruby script =load_heco.rb= makes inlists to load the models
generated by the =make-HeCO-models= directory.  The sub-directory
=final_models= from that workdir can simply be symlinked into
=heco_models= in this one.  The script =run_heco_models.sh= and
=heco.batch= run these models.

The script =run_heco_models.sh= and =ZP4.batch= runs the detailed
merger models.  (The input model is included here in =models/=.)
